### ISSUE TITLE
Test standalone with libstdc++

### ISSUE THREAD

**Issue by vinniefalco** [CPPAlliance/json#73]
The Travis configuration for standalone clang-9 does not work because the installed libstdc++ is not new enough to contain <memory_resource>

**Comment by vinniefalco** [comment]
Maybe this is already fixed? Unsure

**Comment by sdkrystian** [comment]
I tested without any changes other than enabling the CI job and it still fails. I have a fix [here] (https://github.com/sdkrystian/json/commit/566bd17bada75f7b3b1a00d89bff4526f3cb776e) but I'm unsure if this is the "right" solution.
